// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiPhuongThao973.Data;

namespace NguyenThiPhuongThao973.Migrations
{
    [DbContext(typeof(NguyenThiPhuongThao973Context))]
    partial class NguyenThiPhuongThao973ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NguyenThiPhuongThao973.Models.NTPT0973", b =>
                {
                    b.Property<int>("NTPTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NTPTGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NTPTName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NTPTId");

                    b.ToTable("NTPT0973");
                });

            modelBuilder.Entity("NguyenThiPhuongThao973.Models.PersonNTPT973", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("PersonNTPT973");
                });
#pragma warning restore 612, 618
        }
    }
}
